[package]
name = "MessageBoard"
version = "1.0.0"

[addresses]
std = "0x1"
message_board_addr = "0x9dae74c3df3e6bcf432d55b97ce26681eded52103d2a109163a1435912ce6271"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
